apiVersion: apps/v1
kind: Deployment
metadata:
  name: lionel-site-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lionel-web
  template:
    metadata:
      labels:
        app: lionel-web
    spec:
      containers:
      - name: k3d-lionel-container
        image: k3d-lionel-site:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lionel-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: lionel-web